package com.qms.module.qms.common.entity;

import com.qms.common.base.BaseEntity;
import com.qms.common.enums.Priority;
import com.qms.common.enums.QmsRecordType;
import com.qms.common.enums.QmsStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Abstract base entity shared by all five QMS sub-modules.
 *
 * Architecture rationale:
 * ────────────────────────
 * All QMS records share a common lifecycle (status, priority, assignment,
 * dates, workflow) and a common set of cross-cutting operations (close, approve,
 * reject). Placing these fields here:
 *   ✓ Eliminates duplication across 5 entity classes
 *   ✓ Allows a single QmsRecordRepository for cross-module queries (dashboard)
 *   ✓ Enables the generic QmsWorkflowService to operate on any record
 *   ✓ Makes the audit trail uniform across all sub-modules
 *
 * Each sub-module extends this class and adds only its specific fields.
 * The discriminator column (record_type) enables the @Inheritance strategy.
 *
 * Table strategy: TABLE_PER_CLASS
 *   Each sub-module gets its own table with all shared columns duplicated.
 *   This is preferred over SINGLE_TABLE (one giant table) because:
 *     - Sub-module tables stay narrow and fast
 *     - Nullable columns are minimised
 *     - Indexes are per-module, not cross-module
 *   And over JOINED (normalized) because:
 *     - No join overhead for the common 95% queries
 *     - CAPA queries never touch the deviation table
 */
@MappedSuperclass
@Getter
@Setter
public abstract class QmsRecord extends BaseEntity {

    // ── Identity ─────────────────────────────────────────────

    /**
     * Human-readable record number, auto-generated by sub-module service.
     * Format: PREFIX-YYYYMM-NNNN  e.g. CAPA-202404-0001
     */
    @Column(name = "record_number", nullable = false, unique = true, length = 30)
    private String recordNumber;

    /** Discriminates the sub-module type — stored but not used as JPA discriminator. */
    @Enumerated(EnumType.STRING)
    @Column(name = "record_type", nullable = false, length = 30, updatable = false)
    private QmsRecordType recordType;

    // ── Core fields ───────────────────────────────────────────

    @Column(name = "title", nullable = false, length = 255)
    private String title;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    // ── Status & priority ─────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private QmsStatus status = QmsStatus.DRAFT;

    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 20)
    private Priority priority = Priority.MEDIUM;

    // ── Assignment ────────────────────────────────────────────

    /** FK-style reference to users.id — not a JPA FK to avoid cross-module coupling. */
    @Column(name = "assigned_to_id")
    private Long assignedToId;

    @Column(name = "assigned_to_name", length = 150)
    private String assignedToName;

    /** Whoever raised (created) this record. Set at creation time only. */
    @Column(name = "raised_by_id", updatable = false)
    private Long raisedById;

    @Column(name = "raised_by_name", length = 150, updatable = false)
    private String raisedByName;

    /**
     * Legacy free-text department — kept for backward compatibility during
     * the org-structure migration. New code should rely on {@link #departmentId}.
     */
    @Column(name = "department", length = 100)
    private String department;

    /**
     * FK-style reference to departments.id — the originating department of
     * the record. Drives positional workflow checks (e.g. "HOD of THIS dept
     * must approve the PENDING_HOD step").
     */
    @Column(name = "department_id")
    private Long departmentId;

    /**
     * When QA routes a record to another department for cross-functional
     * comment (status PENDING_DEPT_COMMENT), this column captures which
     * department must comment. The HOD of that department is then the only
     * actor that can move the record back to PENDING_QA_REVIEW.
     */
    @Column(name = "commenting_department_id")
    private Long commentingDepartmentId;

    // ── Dates ────────────────────────────────────────────────

    @Column(name = "due_date")
    private LocalDate dueDate;

    @Column(name = "closed_date")
    private LocalDate closedDate;

    @Column(name = "target_completion_date")
    private LocalDate targetCompletionDate;

    // ── Approval ─────────────────────────────────────────────

    @Column(name = "approved_by_id")
    private Long approvedById;

    @Column(name = "approved_by_name", length = 150)
    private String approvedByName;

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    @Column(name = "approval_comments", length = 1000)
    private String approvalComments;

    // ── Analysis fields (shared across most sub-modules) ──────

    @Column(name = "root_cause", columnDefinition = "TEXT")
    private String rootCause;

    @Column(name = "corrective_action", columnDefinition = "TEXT")
    private String correctiveAction;

    @Column(name = "comments", columnDefinition = "TEXT")
    private String comments;

    // ── Risk + categorisation (shared by all 5 modules) ──────

    /** Risk assessment narrative captured during HOD / QA review. */
    @Column(name = "risk_assessment", columnDefinition = "TEXT")
    private String riskAssessment;

    /** Critical / Major / Minor — set during RA evaluation on Change Control,
     *  generally useful on every QMS module for impact rating. */
    @Column(name = "category", length = 20)
    private String category;

    // ── Customer communication block (Change Control + Market Complaint) ──

    @Column(name = "customer_communication_required")
    private Boolean customerCommunicationRequired;

    @Column(name = "customer_representative", length = 150)
    private String customerRepresentative;

    @Column(name = "customer_comment", columnDefinition = "TEXT")
    private String customerComment;

    // ── Verification phase (post-implementation review) ──────

    @Column(name = "verification_action_taken", columnDefinition = "TEXT")
    private String verificationActionTaken;

    @Column(name = "verification_effective_on")
    private LocalDate verificationEffectiveOn;

    @Column(name = "verification_documents_reissue")
    private Boolean verificationDocumentsReissue;

    @Column(name = "verification_other_comments", columnDefinition = "TEXT")
    private String verificationOtherComments;

    @Column(name = "verification_reg_communication", columnDefinition = "TEXT")
    private String verificationRegCommunication;

    // ── Target-date extension (lightweight inline workflow) ──
    //
    // Inline approach avoids a separate workflow engine: when an Initiator
    // requests an extension we capture the new date + reason and flip
    // status to PENDING. Reviewer (HOD or QA Reviewer) then approves/rejects
    // via the dedicated endpoint, which sets the final status and — on
    // approval — copies extension_date into target_completion_date.

    @Column(name = "target_date_extension_date")
    private LocalDate targetDateExtensionDate;

    @Column(name = "target_date_extension_reason", columnDefinition = "TEXT")
    private String targetDateExtensionReason;

    /** PENDING / APPROVED / REJECTED — null if no extension was ever requested. */
    @Column(name = "target_date_extension_status", length = 20)
    private String targetDateExtensionStatus;

    @Column(name = "target_date_extension_requested_by_id")
    private Long targetDateExtensionRequestedById;

    @Column(name = "target_date_extension_requested_at")
    private LocalDateTime targetDateExtensionRequestedAt;

    @Column(name = "target_date_extension_decided_by_id")
    private Long targetDateExtensionDecidedById;

    @Column(name = "target_date_extension_decided_at")
    private LocalDateTime targetDateExtensionDecidedAt;

    // ── Resend counter ─────────────────────────────────────────
    //
    // Incremented each time the HOD presses "Resend to Initiator" at
    // PENDING_HOD. Distinct from REJECTED (which terminates the record);
    // a resend bounces the record back to DRAFT so the Initiator can edit
    // and re-submit. The counter lets QA Evaluation later read "this CC
    // was resent N times" at a glance, alongside the per-resend rows in
    // the status_history JSON.

    @Column(name = "resend_count", nullable = false)
    private Integer resendCount = 0;

    // ── Workflow history (embedded JSON — avoids extra join table) ──

    @Column(name = "status_history", columnDefinition = "TEXT")
    private String statusHistory; // JSON array — managed by QmsWorkflowService

    // ── Convenience helpers ───────────────────────────────────

    public boolean isClosed()     { return status == QmsStatus.CLOSED; }
    public boolean isCancelled()  { return status == QmsStatus.CANCELLED; }
    public boolean isTerminal()   { return isClosed() || isCancelled(); }
    public boolean isOverdue()    {
        return dueDate != null && LocalDate.now().isAfter(dueDate) && !isTerminal();
    }
}
